### ISSUE TITLE
Possible incorrect bit shifts in construct_ZTE_header?

### ISSUE THREAD

**Issue by PaulZC** [arribada/horizon#6]
Hi Alasdair,
Sincere thanks for sharing Horizon. It is a wonderful resource for anyone working with the ARTIC R2.
I _think_ I've spotted a gremlin in your ZTE header code:
https://github.com/arribada/horizon/blob/master/firmware/v4/devices/satellite/artic/syshal_sat.c#L864-L867
I think the bit shifts should be:
```>> 20```
```>> 12```
```>> 4```
```<< 4```
Please take a quick look and let me know if I've got that horribly wrong...
(My understanding is that ZE does not need the 4-bit length field - and it looks like  your code includes it?)
Very best wishes,
Paul

**Comment by al2k** [comment]
Hi Paul,

A good spot. We have confirmed that this is a bug and will resolve it in the next release due shortly. Thank you for disclosing it.

**Comment by PaulZC** [comment]
Hi Alasdair,

You are most welcome! Please feel free to close this issue now - or once the new release has gone live.

Thanks again for sharing Horizon. It is a wonderful thing.

Best wishes,

Paul

**Comment by al2k** [comment]
This is now corrected in the firmware release 11.3 that will be made available shortly.
