### ISSUE TITLE
[Question] Is the hardware really available?

### ISSUE THREAD

**Issue by set-soft** [arribada/horizon#7]
Hi!

The CLS people told us that *You can find open source reference on Github from Arribada*

I cloned the repo and found `Arribada TT4 270420.zip`, this file seems to be generated by Altium, but it isn't even a `.PcbDoc`, and doesn't look to contain any schematic.

1. What's this file?
2. What's the intent of releasing the files in the hardware folder of the repo?

**Comment by al2k** [comment]
Hi @set-soft,

Are you looking for the ARTIC reference design files? They are available via the CLS website [here](https://www.cls-telemetry.com/argos-solutions/argos-products/modems/artic-chipset/#Open-Source-Reference-Design) on request, or we can suggest to move them across to this repo.

Alternatively we can push the Altium source files for the Horizon v4.1 GPS board if you're specifically looking for those, although I assume you're interested in the ARTIC R2 board design?

**Comment by set-soft** [comment]
Hi @al2k 

Thanks for the quick reply

> Are you looking for the ARTIC reference design files? They are available via the CLS website [here](https://www.cls-telemetry.com/argos-solutions/argos-products/modems/artic-chipset/#Open-Source-Reference-Design) on request, or we can suggest to move them across to this repo.

When we asked to CLS they (Nicolle Lucas) sent us this link https://github.com/arribada/horizon/tree/master/hardware/horizon_v4_1

> Alternatively we can push the Altium source files for the Horizon v4.1 GPS board if you're specifically looking for those, although I assume you're interested in the ARTIC R2 board design?

You are right what we really need are the ARTIC R2 stuff, so we can evaluate incorporating it to our future design.

Thanks for clarifying it, I'll insist with Lucas

**Comment by al2k** [comment]
Hi @set-soft,

The Altium source files for the Horizon v4.1 Developer's Kit board are now also available as part of this repo as _Arribada TT4 Altium source.zip_

Kind regards,

Alasdair
